from __future__ import annotations

import os
from datetime import datetime
from typing import Iterable, List

from src.agents.base import Agent
from src.agents.langgraph_agent import LangGraphAgent
from src.api.projects import WebFinding, WebScoutOutput


class WebScoutAgent(Agent):
    name = "web_scout"

    def __init__(
        self,
        provider_name: str = "knowledge-graph",
        use_llm: bool = True,
        api_key: str | None = None,
        model_name: str = "gpt-4o-mini",
    ) -> None:
        self.provider_name = provider_name
        self.use_llm = use_llm

        # Инициализируем LangGraph агента для генерации findings
        if self.use_llm:
            try:
                self.llm_agent = LangGraphAgent(
                    model_name=model_name,
                    api_key=api_key or os.getenv("OPENAI_API_KEY"),
                    system_prompt=(
                        "Вы опытный веб-исследователь и информационный аналитик. На основе поисковых запросов генерируйте информативные результаты с заголовками, релевантными URL-адресами и краткими фрагментами, в которых обобщается ключевая информация. Будьте точны и предоставляйте полезную информацию."
                    ),
                )
            except ValueError:
                # Если API ключ не указан, отключаем LLM
                self.use_llm = False
                self.llm_agent = None
        else:
            self.llm_agent = None

    def run(self, *, queries: Iterable[str]) -> dict:
        findings: List[WebFinding] = []
        timestamp = datetime.utcnow().isoformat()
        
        for query in queries:
            if self.use_llm and self.llm_agent:
                finding = self._generate_finding_with_llm(query, timestamp)
            else:
                finding = self._generate_finding_fallback(query, timestamp)
            
            findings.append(finding)
        
        return WebScoutOutput(findings=findings).model_dump()

    def _generate_finding_with_llm(self, query: str, timestamp: str) -> WebFinding:
        """Генерирует finding используя LLM."""
        prompt = (
            f"Сгенерируй результаты веб-исследования для данного запроса: '{query}'. "
            "Обеспечь:\n"
            "1. Описательный заголовок (максимум 100 символов)\n"
            "2. Соответствующий формат URL (используйте example.com домен)\n"
            "3. Краткий фрагмент (2-3 предложения) с ключевой информацией по данной теме\n\n"
            "Отформатируйте свой ответ следующим образом:\n"
            "Заголовок: [title]\n"
            "URL: [url]\n"
            "Snippet: [snippet]"
        )

        try:
            result = self.llm_agent.run(query=prompt)
            response = result.get("response", "")
            
            # Парсим ответ LLM
            title = f"{query.title()} overview"
            url = f"https://search.example.com/{query.replace(' ', '-')}"
            snippet = f"Automated discovery for '{query}' generated by {self.provider_name} at {timestamp}."

            lines = response.split("\n")
            for line in lines:
                line = line.strip()
                if line.lower().startswith("title:"):
                    title = line.split(":", 1)[1].strip()[:100]
                elif line.lower().startswith("url:"):
                    url = line.split(":", 1)[1].strip()
                elif line.lower().startswith("snippet:"):
                    snippet = line.split(":", 1)[1].strip()

            return WebFinding(
                title=title,
                url=url,
                snippet=snippet,
            )
        except Exception:
            # В случае ошибки используем fallback
            return self._generate_finding_fallback(query, timestamp)

    @staticmethod
    def _generate_finding_fallback(query: str, timestamp: str) -> WebFinding:
        """Простой метод генерации finding без LLM."""
        return WebFinding(
            title=f"{query.title()} overview",
            url=f"https://search.example.com/{query.replace(' ', '-')}",
            snippet=(
                f"Automated discovery for '{query}' generated by knowledge-graph at {timestamp}."
            ),
        )

