from __future__ import annotations

from datetime import datetime
from typing import Iterable, List

from src.agents.base import Agent
from src.api.projects import WebFinding, WebScoutOutput


class WebScoutAgent(Agent):
    name = "web_scout"

    def __init__(self, provider_name: str = "knowledge-graph") -> None:
        self.provider_name = provider_name

    def run(self, *, queries: Iterable[str]) -> dict:
        findings: List[WebFinding] = []
        timestamp = datetime.utcnow().isoformat()
        for query in queries:
            findings.append(
                WebFinding(
                    title=f"{query.title()} overview",
                    url=f"https://search.example.com/{query.replace(' ', '-')}",
                    snippet=(
                        f"Automated discovery for '{query}' generated by {self.provider_name} at {timestamp}."
                    ),
                )
            )
        return WebScoutOutput(findings=findings).model_dump()

